### ISSUE TITLE
Add button to wipe local storage programs for local network when restarting it.

### ISSUE THREAD

**Issue by njelich** [gear-tech/gear-js#1094]
### Problem to Solve

Currently if I restart the local gear network, the programs will stay cached in the IndexedDB and still appear on the list despite not existing onchain.

### Possible Solution

Add a simple button that allows the deletion of all programs (done practically by removing the IndexedDB entry created here that contains the list of programs.

**Comment by osipov-mit** [comment]
> ### Problem to Solve
> Currently if I restart the local gear network, the programs will stay cached in the IndexedDB and still appear on the list despite not existing onchain.
> 
> ### Possible Solution
> Add a simple button that allows the deletion of all programs (done practically by removing the IndexedDB entry created here that contains the list of programs.
> 
> ### Notes
> _No response_

Yeah, we are in the progress
