### ISSUE TITLE
The `String` type is incorrectly sent to the smart contract

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [gear-tech/gear-js#1280]
### Problem

I'm using [gear-dapps/ping](https://github.com/gear-dapps/ping) contract and for some reason `idea.gear-tech.io` sends `\u0010PING` instead of `PING`. Since the contract is expecting a "PING" value, it doesn't reply to user
![image](https://user-images.githubusercontent.com/109800286/235133451-20107423-f6ef-461c-977c-2ba1011035b0.png)

### Steps

1. open https://idea.gear-tech.io/programs/0x0cd68a835cbeb9037edde7f60da6b26286a48e886e8ef0b7f1346dbc7c39d7a8?node=wss%3A%2F%2Frpc-node.gear-tech.io%3A443
2. press "send message"
3. type "PING" (w/o quotes into payload:Str field)
4. calculate gas for message
5. send message to queue
6. open https://idea.gear-tech.io/state/full/0x0cd68a835cbeb9037edde7f60da6b26286a48e886e8ef0b7f1346dbc7c39d7a8?node=wss%3A%2F%2Frpc-node.gear-tech.io%3A443 to read full state of smart contract (There will be a list of incorrectly encoded strings. In Some cases string starts from `\u0010` and `@`)

**Comment by osipov-mit** [comment]
Hi @StackOverflowExcept1on! [ping contract](https://github.com/gear-dapps/ping) has been updated and now works properly
