### ISSUE TITLE
Gear IDEA doesn't properly decode message payload of type `String`

### ISSUE THREAD

**Issue by btwiuse** [gear-tech/gear-js#1380]
### Problem

Taking a deployed instance of [dapps-ping](https://github.com/gear-foundation/dapps-ping) for example: https://idea.gear-tech.io/programs/0xa44c33f33e61949e51f49b1b8cb44efadacde4ce0c236dfb3305c61d324b2e5e?node=wss%3A%2F%2Ftestnet.vara.rs

The input and output types of the handle entrypoint are both know to be String:

![image](https://github.com/gear-tech/gear-js/assets/54848194/d597526b-84ee-49b8-b116-bb92205de457)

If I send a "PING" message, the scale-encoded message payload would be `0x1050494e47`, which has an extra byte added in the front indicating the string length.

The frontend mistakenly interprets the extra byte as being part of the string:

![image](https://github.com/gear-tech/gear-js/assets/54848194/f617d578-3e3a-4353-b06e-d46fdb10a4cd)

Expected: `"PING"`
Got: `"\u0010PING"`

Related: https://github.com/gear-foundation/dapps-ping/pull/36

### Steps

1. deploy the dapps-ping example
2. send a "PING" string
3. check message payload, for example: https://idea.gear-tech.io/messages/0xa45bfc379eca4d8f8dbf70f86735d56b61573a57e60028e9a6ed7aa34c557c43?node=wss%3A%2F%2Ftestnet.vara.rs

### Possible Solution

Convert message payload hex to u8a before decoding with `createType`:

```
> api.createType('String', hexToU8a('0x1050494e47')).toString()
"PING"
```

otherwise the leading byte will be treated literally:

```
> api.createType('String', '0x1050494e47').toString()
"\x10PING"
```

### Notes

There’s a similar question on Stackexchange: https://substrate.stackexchange.com/q/9893/408

**Comment by osipov-mit** [comment]
@btwiuse It's a known issue. There are 2 way to encode/decode string. In the first case, the length of the string is in the beginning of the byte array and in the second case it's not. So if you will try to decode bytes using type `String` than it won't treat the 1st byte as a length (it's kinda default behaviour for scale codec)
