### ISSUE TITLE
feat(@gear-js/react-hooks): cookie-based or hybrid storage for cross-domain synchronization

### ISSUE THREAD

**Issue by rockyessel** [gear-tech/gear-js#1623]
### Problem to Solve

I've noticed an issue where logging out from either the main domain or a subdomain doesn't affect the other. This is because the login details are stored in localStorage, which is domain-specific. As a result, users have to log out separately from both the domain and subdomains, which isn't ideal. It not only creates a poor user experience but also introduces potential security risks.

```bash
User Logs Out from Domain
   domain.com/[slug]
          ↓
      Logout Action
          ↓
  localStorage Cleared (domain.com)
          ↓
  ⬤ User still logged in on app.domain.com
          ↓
   User must log out again from app.domain.com
          ↓
      Logout Action
          ↓
  localStorage Cleared (app.domain.com)
          ↓
  ⬤ User now logged out from both domain.com and app.domain.com

```

### Possible Solution

I think a good solution would be to use cookies instead of, or alongside localStorage for managing user session data. By setting cookies with a shared domain (e.g., `.domain.com`), we can ensure that logging out on any domain or subdomain will be synchronized across all related domains.

To make this flexible for different environments, I suggest configuring the cookies to allow developers to customize settings based on whether they are in development or production. Here’s an example configuration:

```javascript
{
  secure: isProduction,
  httpOnly: true,
  sameSite: 'lax',
  path: '/',
  domain: '.symbion.com', // For sharing cookies between domain & subdomain
}
```

In addition, it would be helpful to provide developers with options for choosing their preferred storage mechanism. For example:

```javascript
useAccount('cookie', { /* cookie config */ });
useAccount('local');
```

This way, developers can easily switch between cookie-based storage and localStorage depending on their specific needs.

Additionally, I recommend implementing a fallback mechanism where the application checks whether localStorage or cookies are available and uses whichever is appropriate in the given context. This would help ensure that session management is reliable and consistent across different environments.

```bash
User Logs Out from Domain
   domain.com/[slug]
          ↓
      Logout Action
          ↓
Cookies Cleared (Shared across .domain.com)
          ↓
  ⬤ User logged out on both domain.com and app.domain.com
          ↓
   User automatically logged out from app.domain.com

```

### Notes

I'm currently building this for a hackathon, so if this feature can be added earlier, I would greatly appreciate it. However, if that's not possible, I have a workaround in mind that involves rewriting the entire authentication logic for the DID. This workaround is not ideal, but it will allow me to move forward with the project.

**Comment by nikitayutanov** [comment]
Hi, @rockyessel! I appreciate your detailed request.

I don't think it's possible to achieve the desired UX even with cookies, because wallet extensions treat subdomains as standalone apps requiring separate authentication requests. Therefore, I would recommend to stick to the current ecosystem limitations.

**Comment by rockyessel** [comment]
Okay @nikitayutanov
