### ISSUE TITLE
"TransactionPaymentApi" error after update v1.7.0

### ISSUE THREAD

**Issue by kencani** [gear-tech/gear-js#1678]
### Problem

RpcError: 4003: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x64d8 - vara_runtime.wasm!rust_begin_unwind
    1: 0x3084 - vara_runtime.wasm!core::panicking::panic_fmt::h87a7cf262cbe7c30
    2: 0x41c76a - vara_runtime.wasm!TransactionPaymentApi_query_info is does not have a type which is supported by SendMessage.

### Steps

```ts
import { useAccount, useProgram, useSendProgramTransaction } from '@gear-js/react-hooks';


  const buyTransaction = useSendProgramTransaction({
    program,
    serviceName: 'market',
    functionName: 'buy',
  });


 const result = await buyTransaction.sendTransactionAsync({
            args: [token_id, count],
});

```

dependencies:

    "@gear-js/api": "0.39.0",
    "@gear-js/react-hooks": "0.14.0",

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by nikitayutanov** [comment]
What is yours `@polkadot/api` version?

**Comment by kencani** [comment]
> What is yours `@polkadot/api` version?

"@polkadot/api": "11.0.2"

**Comment by nikitayutanov** [comment]
Closing this issue, feel free to reopen it or create a new one if you're still encountering any problems.
