### ISSUE TITLE
Use one single method for get metadata

### ISSUE THREAD

**Issue by EugenWay** [gear-tech/gear-js#179]
### File Location(s)

1. Program.tsx
2. ApiService.tsx  -> SendMessageToProgram 

### Proposal

Now to get metadata from the backend in one case we use dispatch(getProgramAction(hash)) -> call program.data method, and another case (on  MessageForm.tsx -> SendMessageToProgram) we use 'program.getMeta'

Find the optimal option to get metadata

**Comment by AndrePanin** [comment]
Not actual with new backend.
