### ISSUE TITLE
How to run `idea.gear-tech.io` in the localhost ?

### ISSUE THREAD

**Issue by liushooter** [gear-tech/gear-js#206]
I try to run localhost node，and  idea website connect that。 I think  need  run `idea website` backend in the localhost。

I not find the tutorial about  `idea website` backend。

**Comment by osipov-mit** [comment]
> I try to run localhost node，and idea website connect that。 I think need run `idea website` backend in the localhost。
> 
> I not find the tutorial about `idea website` backend。

We are developing possibility to use localnode without running backend locally. In 2 days it will be finished.
