### ISSUE TITLE
fix typo in method name

### ISSUE THREAD

**Issue by codev0** [gear-tech/gear-js#250]
Hey.

@osipov-mit I've found a minor typo on method name, just change `subsribeBalanceChange` to `subscribeBalanceChange` in the
https://github.com/gear-tech/gear-js/blob/182c5e6a3779fdd4942baa43779941a8c32a5d13/api/api/src/Events.ts#L53

**Comment by xhjkl** [comment]
Good catch! Addressed in #258.
