### ISSUE TITLE
Builds a form for handle() when loading the program

### ISSUE THREAD

**Issue by EugenWay** [gear-tech/gear-js#394]
### Problem

In the new program download form, handle_input is processed , but it should check for init.

### Steps

1. Check if init exist provide corresponding fields, if not then hide it

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by aderrod94** [comment]
[Solved](https://github.com/gear-tech/gear-js/pull/434)
