### ISSUE TITLE
Form for metadata is not loaded twice

### ISSUE THREAD

**Issue by EugenWay** [gear-tech/gear-js#395]
### Problem

On upload program page:
If you upload or delete metadata, it is not possible to upload the metafile a second time.

### Steps

1. 
2.
3.

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by aderrod94** [comment]
[Solved](https://github.com/gear-tech/gear-js/pull/435)
